# Generated by Django 3.0.4 on 2020-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('biography', models.TextField(max_length=1000)),
                ('images', models.ImageField(default='images/def.jpg', null=True, upload_to='images/')),
                ('images1', models.ImageField(default='images/def.jpg', null=True, upload_to='images/')),
                ('images2', models.ImageField(default='images/def.jpg', null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
